storage:
  location: storage
server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mylife
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
